title: silentsharer
description: study blog # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://silentsharer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: silentsharer # add your name
author-img: silentsharer.png # add your photo
about-author: A coder who does not write code # add description
twitter: https://twitter.com/ # add your Twitter handle
facebook: https://www.facebook.com/ # add your Facebook handle
github: silentsharer # add your Github handle
linkedin: silentsharer # add your Linkedin handle
email: ssilentsharer@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
